/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ParameterizedData;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Excel2 classUnderTest = new Excel2();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.equals(classUnderTest));
    }}
